# Generated by Django 4.2.6 on 2024-08-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_cars_brakes_rating_alter_cars_engine_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellyourcar',
            name='images',
            field=models.ImageField(default=1, upload_to='sell_car_images/'),
            preserve_default=False,
        ),
    ]
